defaultSemverRangePrefix: ""

ignorePath: false

nodeLinker: pnp

pnpFallbackMode: none

npmRegistryServer: "http://localhost:4873"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-3.3.1.cjs
